variables:
- name: CI
  value: true

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod

  displayName: 'npm install and build'

- script: |
    npx playwright install
    npx playwright install-deps
    npx playwright test
  displayName: 'run tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: 'JUnit'
    testResultsFiles: 'uiTestResults.xml'
    testRunTitle: UI test results
  displayName: 'Publish UI test results'